security:
    providers:
        my_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: '%env(LDAP_BASE_DN)%'
                search_dn: '%env(LDAP_SEARCH_DN)%'
                search_password: '%env(LDAP_SEARCH_PASSWORD)%'
                default_roles: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout:
                path: /logout
                target: /
            stateless: true
            form_login_ldap:
                login_path: /login
                check_path: /login
                service: Symfony\Component\Ldap\Ldap
                dn_string: '%env(LDAP_BASE_DN)%'
                query_string: '(&(sAMAccountName={username})(|(memberOf=users)(memberOf=soignants))'
                search_dn: '%env(LDAP_SEARCH_DN)%'
                search_password: '%env(LDAP_SEARCH_PASSWORD)%'

            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: [ROLE_USER, IS_AUTHENTICATED_FULLY] }