security:
    providers:
        my_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: "dc=fr,dc=lechatelet,dc=local"
                search_dn: "cn=users,ou=soignants dc=fr,dc=lechatelet,dc=local"
                search_password: 'uid={sAMAccountName}'
                default_roles: ROLE_USER
                uid_key: uid={username}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: my_ldap
            pattern: ^/
            logout:
                path: app_authentification_logout
                target: /login
            stateless: true
            form_login_ldap:
                service: Symfony\Component\Ldap\Ldap
                dn_string: 'dc=example,dc=com'
                query_string: '(&(uid={sAMAccountName})(memberOf=cn=users,ou=soignants,dc=fr,dc=lechatelet,dc=local))'
                search_dn: "ou=soignants dc=fr,dc=lechatelet,dc=local"
                search_password: 'uid={sAMAccountName}'
                login_path: app_authentification_login
                check_path: app_authentification_login
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: [ROLE_USER, IS_AUTHENTICATED_FULLY] }